config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :products do
  resources :comments
  end

  resources :users
  resources :products

  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/landing_page'

  root 'static_pages#landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'

  resources :orders, only: [:index, :show, :create, :destroy]
 
  # actioncable
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments
  def highest_rating_comment
    comments.rating_desc.first
  end
  def average_rating
    comments.average(:rating).to_f
  end

  validates :name, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.where("name ilike ?", "%#{search_term}%")
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(page: params[:page], per_page: 3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to :products, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count   = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s,:number)
        "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
  <% @comments.each do |comment| %>
    <div class="row">
    <hr>
      <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>  <% if signed_in? && current_user.admin? %><%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %> <% end %></p>
        <p><%= "Rating: #{comment.rating}/5" %></p>
        <div class="rated" data-score="<%= comment.rating %>"></div>
        <p><%= comment.body %></p>
    </div>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="col-md-4", id="form-field">
      <div class="field form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div> 

      <div class="field form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :image_url %>
        <%= f.text_field :image_url, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :colour %><br>
        <%= f.text_field :colour, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :price %>
        <%= f.text_field :price, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit class: "btn btn-default" %>
      </div>
     <% end %>
    </div>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <div class="form-group">
      <p>
        <%= f.label :body, "Comments" %><br>
        <%= f.text_area :body, class: "form-control" %>
      </p>
    </div>
    <p>
      <div class="rating"></div>
    </p>  
    <p>
      <%= f.submit "Submit", class: "btn btn-md btn-primary " %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
<div class="col-md-3 col-sm-4 col-xs-12">
  <%= image_tag(product.image_url, class: "img-responsive") if product.image_url %>
  <h2><%= product.name %></h2>
  <p><%= product.description %></p>
  <strong><%= product.price %> €</strong><br>
  <%= link_to 'Show', product %>
  <%= link_to 'Edit', edit_product_path(product) %>
  <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
</div><!-- /col -->

<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>
<div class="form">
<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
<h1>Products</h1>
</div>

<div class="container-fluid">
  <div class="row">
  <% cache(cache_key_for_products) do %>
    <%= render @products %>
  <% end %>
  </div>
</div>

<p><%= link_to 'Add Product', new_product_path %></p>

<br>





<!-- <body>

  <div class= "container-fluid">
    <div class="row" style="background-color:beige;">
      <div class="col-sm-2 col-md-4">
        <h1>Box</h1>
        <p>Really Neat Blue Box</p>
        <strong>$ 42</strong>
        <img src="img/bluebox.jpg" class="img-responsive">
      </div>

      <div class="col-sm-2 col-md-4">
        <h1>Book</h1>
        <p>Book of Essays</p>
        <strong>$ 42</strong>
        <img src="img/book.jpg" class="img-responsive">
      </div>

      <div class="col-sm-2 col-md-4">
        <h1>Pencils</h1>
        <p>Colored Drawing Pencils</p>
        <strong>$ 42</strong>
        <img src="img/pencils.jpg" class="img-responsive">
      </div>
    </div>
  </div>
</body>
 -->
  

app/views/products/new.html.erb
<h1>New Product</h1>

<div class="form">

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="container product">

  <div class="row" data-product-id="<%= @product.id %>">

    <p id="notice"><%= notice %></p>

    <% cache @product do %>

    <div class="col-md-3">
      <p>
        <strong>Name:</strong>
        <%= @product.name %>
      </p>
    </div>

    <div class="col-md-12">
      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>
    </div>

    <div class="col-md-12">
      <p>
        <strong>Colour:</strong>
        <%= @product.colour %>
      </p>
    </div>

      <p>
        <strong></strong>
        <%= image_tag(@product.image_url, width: "250", class: "img-zoom", data_zoom_image: @product.image_url) %>
      </p>

    <div class="col-md-12">
      <p>
        <strong>Price:</strong>
        <%= @product.price %> 
      </p>
    </div>

      <div class="text-center">
        <%= form_tag "/payments/create" do %>
          <%= hidden_field_tag(:product_id, @product_id) %>
          <%= render partial: "shared/stripe_checkout_button" %>
        <% end %><br>

        <%= link_to 'Edit', edit_product_path(@product) %> |
        <%= link_to 'Back', products_path %><br>
      </div>

      <p>
        <strong>Average Rating:</strong>
        <div class="rated" id="#average-rating" data-score="<%= @product.average_rating %>">
        </div>
      </p>

    <% end %>

    </div>

    <%= render partial: "new_comment" %>

    <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>

    <%= render partial: "comments" %>

    <div class="apple_pagination">
    <%= will_paginate @comments %>
    </div>
    <br>
    <br>

</div>