config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :products do
  resources :comments
  end

  resources :users
  resources :products

  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/landing_page'

  root 'static_pages#landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'

  resources :orders, only: [:index, :show, :create, :destroy]
 
  # actioncable
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nameofapp</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
     <%=stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true %>
     <%=javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <%= csrf_meta_tags %>
  </head>
  <% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
    <% end %>
  <% if alert %>
    <p id="alert" class="alert alert-info"><%= alert %></p>
    <% end %>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", static_pages_landing_page_path %> </li>
            <li><%= link_to "Products", products_path %></li>
            <li> <%= link_to "About", static_pages_about_path %> </li>
            <li><%= link_to "Contact", static_pages_contact_path %></li>
            <li><%= form_tag("/products", method: "get", class: "navbar-collapse", style:"margin: 8px 0;", role: "search") do %>
              <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
              <div class="form-group" style="display: inline-block">
               <%= text_field_tag([:q], nil, placeholder: 'Search for Bikes', class: 'input-medium form-control') %>
              </div>
            <% end %></li>
          </ul> 
          <ul class="nav pull-right">
            <li>
            <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete, :style => "color: #f7290e") %>
           <% else %>
             <%= link_to('Login', new_user_session_path, :style => "color: #0ef722") %>
            <% end %>
            </li>
           </ul>

        </div>
      </div>
    </nav>

    <%= yield %>

    <footer class="footer">
      <div class="container" id="text">
        <p>&copy; 2015 Bike Berlin</p>
      </div>

      <div class="col-md-1 twitter"><a href="https://twitter.com/CharlieLynchlcl" class="twitter-follow-button" data-size="large" data-show-screen-name="false" data-show-count="false">Follow</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script></div>

      <div class="fb-like col-md-1" data-href="https://www.facebook.com/charlie.lynch.10.html" data-width="87px" data-layout="button_count" data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>
    </footer>
  </body>
</html>